"""Generate the web's TypeScript types from the backend's models: the `Job`
and the frames the live WebSocket sends.

    uv run python scripts/gen_web_types.py

Writes web/lib/generated/argus.ts. CI regenerates it and fails when the
committed file differs, so the web cannot drift from what the API sends.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter
from pydantic.json_schema import GenerateJsonSchema, JsonSchemaValue
from pydantic_core import core_schema

from argus.models.job import Frame

WEB = Path(__file__).resolve().parents[1] / "web"
OUT = WEB / "lib" / "generated" / "argus.ts"
BANNER = "/* Generated by scripts/gen_web_types.py from the backend models. Do not edit. */"


class _Schema(GenerateJsonSchema):
    # Field titles would make json2ts emit a named alias for every field.
    def field_title_should_be_set(self, schema: core_schema.CoreSchema) -> bool:
        return False


def _for_json2ts(node: Any) -> None:
    """Rewrite what json2ts misreads: tuples go in the draft-07 form (`items`
    as a list, not `prefixItems`), and a `$ref` with a `default` beside it
    would be emitted as a second copy of the referenced type."""
    if isinstance(node, dict):
        if "prefixItems" in node:
            node["items"] = node.pop("prefixItems")
        if "$ref" in node:
            node.pop("default", None)
        for value in node.values():
            _for_json2ts(value)
    elif isinstance(node, list):
        for value in node:
            _for_json2ts(value)


def schema() -> JsonSchemaValue:
    value = TypeAdapter(Frame).json_schema(mode="serialization", schema_generator=_Schema)
    value["title"] = "Frame"
    _for_json2ts(value)
    return value


def main() -> None:
    typescript = subprocess.run(
        [
            "pnpm",
            "exec",
            "json2ts",
            "--unreachableDefinitions",
            "--additionalProperties=false",
            f"--bannerComment={BANNER}",
        ],
        input=json.dumps(schema()),
        cwd=WEB,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(typescript)


if __name__ == "__main__":
    main()
