"""Planner agent: extracts verifiable factual claims from any content.

Supports two modes:
  - PDF mode: extracts from uploaded documents (reports, papers, etc.)
  - Text mode: extracts from LLM-generated content (any domain)
"""
from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator

from argus.agents.base import AgentResult, AgentRunner
from argus.miromind.client import MiromindClient
from argus.models.domain import Claim, ClaimType
from argus.pdf.parser import ParsedDoc

_VALID_CLAIM_TYPES: set[str] = {ct.value for ct in ClaimType}

SYSTEM_PROMPT = """\
You are Argus's PLANNER agent. Your only task is to extract verifiable factual
claims from the given document.

You may use these built-in tools: thinking, execute_python.
You SHOULD NOT call web_search or fetch_url_content — that is the next agent's job.

HARD CONSTRAINTS
  - Output MUST be a single valid JSON object — no prose, no fences, no comments,
    no trailing commas inside arrays or objects.
  - Schema:
    {
      "claims": [
        {
          "id": "c1",
          "text": "the exact sentence as it appears in the document",
          "page": 1,
          "span": [69, 116],
          "type": "citation",
          "importance": "high",
          "extracted_metadata": {"authors": ["Smith"], "year": 2021}
        }
      ]
    }
  - `span` MUST be a JSON array of EXACTLY TWO non-negative integers
    [start_char_offset, end_char_offset] within that page's text.
    Both numbers MUST be present. If you cannot determine an exact end offset,
    use start + len(text). NEVER emit `[27,]` or `[27]` — both are invalid.
  - `type` MUST be exactly one of: "citation", "numerical-data", "time-sensitive",
    "cross-reference", "qualitative".
  - `importance` MUST be exactly one of: "high", "medium", "low".
  - Only emit verifiable factual claims. Skip opinion / outlook / generic boilerplate.
  - For type="citation", extracted_metadata SHOULD include any of
    {authors: list[string], year: int, title: string, doi: string|null}.

OUTPUT ONLY THE JSON OBJECT.
"""

SYSTEM_PROMPT_LLM = """\
You are Argus's PLANNER agent. The text you receive was generated by an LLM
(large language model). Your task is to extract every verifiable factual claim
so downstream agents can check each one for hallucinations and errors.

Focus especially on claims that LLMs commonly fabricate:
  - Citations to academic papers, books, or reports (authors, titles, years, DOIs)
  - Specific numerical data (dollar amounts, percentages, counts, dates)
  - Named entities and events (organizations, people, places, policy names)
  - Time-sensitive facts that may be outdated or invented
  - Logical assertions that can be cross-checked against other claims in the text

You may use these built-in tools: thinking, execute_python.
You SHOULD NOT call web_search or fetch_url_content — that is the next agent's job.

HARD CONSTRAINTS
  - Output MUST be a single valid JSON object — no prose, no fences, no comments,
    no trailing commas inside arrays or objects.
  - Schema:
    {
      "claims": [
        {
          "id": "c1",
          "text": "the exact sentence as it appears in the text",
          "page": 1,
          "span": [69, 116],
          "type": "citation",
          "importance": "high",
          "extracted_metadata": {"authors": ["Smith"], "year": 2021}
        }
      ]
    }
  - `page` MUST be 1 (the entire text is treated as a single page).
  - `span` MUST be a JSON array of EXACTLY TWO non-negative integers
    [start_char_offset, end_char_offset] within the text.
    Both numbers MUST be present. If you cannot determine an exact end offset,
    use start + len(text). NEVER emit `[27,]` or `[27]` — both are invalid.
  - `type` MUST be exactly one of: "citation", "numerical-data", "time-sensitive",
    "cross-reference", "qualitative".
  - `importance` MUST be exactly one of: "high", "medium", "low".
  - Only emit verifiable factual claims. Skip opinion / outlook / generic boilerplate.
  - For type="citation", extracted_metadata SHOULD include any of
    {authors: list[string], year: int, title: string, doi: string|null}.
  - Be thorough — extract ALL verifiable claims. Missing a fabricated claim means
    a hallucination goes undetected.

OUTPUT ONLY THE JSON OBJECT.
"""


class _RawClaim(BaseModel):
    """Lenient planner-side claim shape that tolerates LLM output quirks.

    Real MiroMind output occasionally drops characters mid-buffer, leaving
    individual claims with missing keys (e.g. ``"":"c2"`` instead of
    ``"id":"c2"``) or missing values (e.g. ``"page":,"span":...``). Every
    field gets a safe default so a single malformed claim cannot poison the
    whole batch — ``PlannerOutput.to_claims`` filters out claims whose
    ``text`` is still empty after lenient parsing.
    """

    id: str = ""
    text: str = ""
    page: int = 1
    span: list[int] | None = None  # accept anything; we normalise downstream
    type: ClaimType = ClaimType.QUALITATIVE
    importance: Literal["high", "medium", "low"] = "low"
    extracted_metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("type", mode="before")
    @classmethod
    def _coerce_type(cls, v: object) -> object:
        if isinstance(v, str) and v not in _VALID_CLAIM_TYPES:
            return ClaimType.QUALITATIVE
        return v

    @field_validator("importance", mode="before")
    @classmethod
    def _coerce_importance(cls, v: object) -> object:
        if not isinstance(v, str) or v not in {"high", "medium", "low"}:
            return "low"
        return v

    @field_validator("extracted_metadata", mode="before")
    @classmethod
    def _coerce_extracted_metadata(cls, v: object) -> object:
        # LLM sometimes emits ``"extracted_metadata": ""`` (or null) for claims
        # where it couldn't pull out structured metadata. Treat any non-dict
        # as an empty dict so a single sloppy field doesn't poison the batch.
        if isinstance(v, dict):
            return v
        return {}

    @field_validator("span", mode="before")
    @classmethod
    def _coerce_span_field(cls, v: object) -> object:
        # The LLM occasionally drops a comma between claim fields, which causes
        # json-repair to merge subsequent fields into ``span`` — e.g.
        # ``[661, "661type:numerical-data", {"importance": ...}, {...}]``.
        # Strict ``list[int]`` would reject the entire batch. Accept None /
        # any non-list / lists with non-int elements as "span unknown"; the
        # downstream ``_coerce_span`` helper turns that into ``(0, 0)``.
        if v is None:
            return None
        if not isinstance(v, list):
            return None
        if not all(isinstance(x, int) for x in v):
            return None
        return v

    @field_validator("page", mode="before")
    @classmethod
    def _coerce_page(cls, v: object) -> object:
        # The LLM sometimes drops the value entirely: ``"page":,"span":...``
        # which json-repair fills in as ``None``. Treat that as page 1.
        if v is None or v == "":
            return 1
        if isinstance(v, int):
            return v if v >= 1 else 1
        if isinstance(v, str):
            try:
                n = int(v)
            except ValueError:
                return 1
            return n if n >= 1 else 1
        return 1


class PlannerOutput(BaseModel):
    """Raw planner output. Call `to_claims()` to get strict-validated Claims."""

    claims: list[_RawClaim] = Field(default_factory=list)

    def to_claims(self) -> list[Claim]:
        """Convert relaxed planner output to strict-validated Claim instances.

        Claims with empty ``text`` are dropped (they're worthless to downstream
        agents). Claims with empty ``id`` get an auto-generated stable id so
        the orchestrator can address them. Spans that are missing, malformed,
        or out of order fall back to ``(0, 0)``.
        """
        out: list[Claim] = []
        for idx, raw in enumerate(self.claims):
            text = raw.text.strip()
            if not text:
                # Empty text means the LLM corrupted this claim past recovery.
                continue
            cid = raw.id.strip() or f"c_auto_{idx}"
            span = _coerce_span(raw.span)
            out.append(
                Claim(
                    id=cid,
                    text=text,
                    page=raw.page,
                    span=span,
                    type=raw.type,
                    importance=raw.importance,
                    extracted_metadata=raw.extracted_metadata,
                )
            )
        return out


_SPAN_LEN = 2


def _coerce_span(value: list[int] | None) -> tuple[int, int]:
    if value is None or len(value) < _SPAN_LEN:
        return (0, 0)
    start, end = int(value[0]), int(value[1])
    if start < 0 or end < start:
        return (0, 0)
    return (start, end)


def build_planner_input(doc: ParsedDoc, *, input_mode: str = "pdf") -> str:
    """Concatenate pages with explicit page markers the model can cite back."""
    if input_mode == "text":
        return doc.full_text
    parts = [f"[PAGE {p.page_number}]\n{p.text}" for p in doc.pages]
    return "\n\n".join(parts)


def planner_runner(client: MiromindClient) -> AgentRunner[PlannerOutput]:
    return AgentRunner(
        client=client,
        model_cls=PlannerOutput,
        agent_name="planner",
        max_output_tokens=12000,
    )


async def run_planner(
    client: MiromindClient, doc: ParsedDoc, *, input_mode: str = "pdf"
) -> AgentResult[PlannerOutput]:
    runner = planner_runner(client)
    prompt = SYSTEM_PROMPT_LLM if input_mode == "text" else SYSTEM_PROMPT
    return await runner.run(
        instructions=prompt,
        input_text=build_planner_input(doc, input_mode=input_mode),
    )
